on:
  release:
    types: [created]
  
jobs:
  release:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: 
          - x86_64-pc-windows-gnu
          - x86_64-unknown-linux-musl
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl
          - armv7-unknown-linux-gnueabi
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabi
          - armv7-unknown-linux-musleabihf
          - mipsel-unknown-linux-musl
          - mips-unknown-linux-musl
          - mips64-unknown-linux-muslabi64
          - mips64el-unknown-linux-muslabi64
          - i686-unknown-linux-gnu
          - i686-unknown-linux-musl
          - i686-pc-windows-gnu
          - arm-unknown-linux-gnueabi
          - arm-unknown-linux-musleabi
          - arm-unknown-linux-gnueabihf
          - arm-unknown-linux-musleabihf
    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true

      - name: Install cargo cross
        run: cargo install cross
      
      - name: Build artifact
        run: cross build --target ${{ matrix.target }} --release --locked 

      - name: Upload artifact (Linux)
        uses: actions/upload-artifact@v1
        with:
          name: srun-cli-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/srun-cli
        if: matrix.target != 'x86_64-pc-windows-gnu' && matrix.target != 'i686-pc-windows-gnu'
      
      - name: Upload artifact (Windows)
        uses: actions/upload-artifact@v1
        with:
            name: srun-cli-${{ matrix.target }}
            path: target/${{ matrix.target }}/release/srun-cli.exe
        if: matrix.target == 'x86_64-pc-windows-gnu' || matrix.target == 'i686-pc-windows-gnu'
